### ISSUE TITLE
`featurizer.apply(docs=train_docs)` fails on clearing

### ISSUE THREAD

**Issue by HiromuHota** [HazyResearch/fonduer#250]
**Describe the bug**

Giving docs as`featurizer.apply(docs=train_docs)` instead of split as `featurizer.apply(split=0)` fails at `fonduer.features.featurizer.Featurizer#clear`

**To Reproduce**

1. Give docs as`featurizer.apply(docs=train_docs)` instead of split as `featurizer.apply(split=0)`

**Expected behavior**

`featurizer` works when docs are given.

**Error Logs/Screenshots**
If applicable, add error logs or screenshots to help explain your problem.

```
[2019-05-02 11:46:10,363][INFO] fonduer.features.featurizer:190 - Clearing Features (split ALL)
Traceback (most recent call last):
  File "/Users/hiromu/miniconda3/envs/fonduer-mlflow/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/Users/hiromu/miniconda3/envs/fonduer-mlflow/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for integer: "ALL"
LINE 5: WHERE candidate.split = 'ALL')
```

**Environment (please complete the following information):**
Reproducible on any env.

**Additional context**

**Comment by HiromuHota** [comment]
A workaround is to use `clear=False` as `featurizer.apply(train_docs, clear=False)`.
