### ISSUE TITLE
ValueError: zero-size array during _strlib_multinary_features

### ISSUE THREAD

**Issue by HiromuHota** [HazyResearch/fonduer#486]
## Description of the bug

"ValueError: zero-size array" happens during featurization.

## To Reproduce
1. Run the hardware tutorial with the latest commit (d94f3be21326db7c0660a7a51c75ac27511db110) of Fonduer.

## Expected behavior

Featurization runs without an error.

## Error Logs/Screenshots

https://github.com/HiromuHota/fonduer-tutorials/runs/880000246
```
2020-07-17T00:45:17.3377388Z Traceback (most recent call last):
2020-07-17T00:45:17.3377548Z   File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
2020-07-17T00:45:17.3377686Z     self.run()
2020-07-17T00:45:17.3378135Z   File "/home/user/.venv/lib/python3.7/site-packages/fonduer/utils/udf.py", line 219, in run
2020-07-17T00:45:17.3378281Z     y = self.apply(doc, **self.apply_kwargs)
2020-07-17T00:45:17.3378605Z   File "/home/user/.venv/lib/python3.7/site-packages/fonduer/features/featurizer.py", line 346, in apply
2020-07-17T00:45:17.3378744Z     for cands in cands_list
2020-07-17T00:45:17.3379249Z   File "/home/user/.venv/lib/python3.7/site-packages/fonduer/features/featurizer.py", line 346, in <listcomp>
2020-07-17T00:45:17.3379505Z     for cands in cands_list
2020-07-17T00:45:17.3379821Z   File "/home/user/.venv/lib/python3.7/site-packages/fonduer/utils/utils_udf.py", line 243, in get_mapping
2020-07-17T00:45:17.3379946Z     for cid, key, value in generator(cand):
2020-07-17T00:45:17.3380274Z   File "/home/user/.venv/lib/python3.7/site-packages/fonduer/features/feature_extractors.py", line 63, in extract
2020-07-17T00:45:17.3380428Z     for candidate_id, feature, value in feature_extractor(candidates):
2020-07-17T00:45:17.3380802Z   File "/home/user/.venv/lib/python3.7/site-packages/fonduer/features/feature_libs/structural_features.py", line 70, in extract_structural_features
2020-07-17T00:45:17.3380955Z     for feature, value in _strlib_multinary_features(spans):
2020-07-17T00:45:17.3381317Z   File "/home/user/.venv/lib/python3.7/site-packages/fonduer/features/feature_libs/structural_features.py", line 113, in _strlib_multinary_features
2020-07-17T00:45:17.3381622Z     yield f"COMMON_ANCESTOR_[{' '.join(common_ancestor(spans))}]", DEF_VALUE
2020-07-17T00:45:17.3381973Z   File "/home/user/.venv/lib/python3.7/site-packages/fonduer/utils/data_model_utils/structural.py", line 184, in common_ancestor
2020-07-17T00:45:17.3382114Z     val = np.min(arg_min[np.nonzero(arg_min)])
2020-07-17T00:45:17.3382470Z   File "<__array_function__ internals>", line 6, in amin
2020-07-17T00:45:17.3382803Z   File "/home/user/.venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2793, in amin
2020-07-17T00:45:17.3382927Z     keepdims=keepdims, initial=initial, where=where)
2020-07-17T00:45:17.3383248Z   File "/home/user/.venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
2020-07-17T00:45:17.3383392Z     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
2020-07-17T00:45:17.3383686Z ValueError: zero-size array to reduction operation minimum which has no identity
```

## Environment (please complete the following information)

Fonduer: d94f3be21326db7c0660a7a51c75ac27511db110

## Additional context

This may be a regression caused by #456.

**Comment by HiromuHota** [comment]
The error happens when processing Document "Infineon-BC857SERIES_BC858SERIES_BC859SERIES_BC860SERIES-DS-v01_01-en".

**Comment by HiromuHota** [comment]
The root cause is that `fonduer.utils.data_model_utils.common_ancestor` does not assume all the mentions share exactly the same ancestor.

The error happens when executing `common_ancestor(c)` with a candidate: `PartTemp(Part(ImplicitSpanMention("BC859", sentence=2516, words=[4,6], position=[0])), Temp(ImplicitSpanMention("200", sentence=2514, words=[1,1], position=[0])))`.
As illustrated below, the two spans "BC859" and "200" share the same xpath (`'/html/body/table[7]/tr[20]/td[1]/p[3]'`) hence the same ancestor.
![image](https://user-images.githubusercontent.com/20668349/88229653-f38a3a00-cc25-11ea-9f16-cc762c27ed3a.png)
