### ISSUE TITLE
HOCRParser fails to multiline Japanese strings

### ISSUE THREAD

**Issue by YasushiMiyata** [HazyResearch/fonduer#534]
## Description of the bug
HocrVisualParser() fails to multiline Japanese strings like "チェーン店\n本・支店".
Hocr parser result does not aligne with spacy parse result and throws an error 
`"RuntimeError: ('Tokens are not aligned!', "hocr tokens: ['チェーン店', '本・支店']", "spacy tokens: ['チェーン', '店本', '・', '支店']")"`
This situation same as "hocr tokens: ['AAAA', 'BBBB']", "spacy tokens: ['AAA', 'AB', 'B', 'BB']".
This might because spacy recognizes parts of different line words as one word like 'AB'. 

## To Reproduce
1. Add test codes into "./tests/parser/test_parser.py"
~~~
def test_parse_hocr_with_multiline_ja():
    docs_path = "tests/data/hocr_simple/jtest.hocr"
    preprocessor = HOCRDocPreprocessor(docs_path, space=False)
    doc = next(iter(preprocessor))
    parser_udf = get_parser_udf(
        structural=True,
        tabular=True,
        lingual=True,
        language="ja",
        visual_parser=HocrVisualParser(),
    )
    doc = parser_udf.apply(doc)
    assert doc.name == "jtest"
~~~
2. Run 'pytest ./tests/parser/test_parser.py::test_parse_hocr_with_multiline_ja'

### jtest.hocr
~~~
<?xml version="1.0" ?>
  <html>
    <head>
      <meta content="Generated OCRed text" name="ocr-system"/>
      <meta content="ocr_page ocr_line ocrx_word" name="ocr-capabilities"/>
    </head>
    <body>
      <div class="ocr_page" id="page_1" title="bbox 0 0 595 842">
          <div class="ocr_line" id="line_1_1" title="bbox 70 156 73 157">
            <span class="ocrx_word" id="word_1_1" title="bbox 70 156 73 157">チェーン店</span>
          </div>
          <div class="ocr_line" id="line_1_2" title="bbox 83 171 89 172">
            <span class="ocrx_word" id="word_1_2" title="bbox 83 171 89 172">本・支店</span>
          </div>
      </div>
    </body>
  </html>
~~~

## Expected behavior
Get aligned tokens like "hocr tokens: ['チェーン店', '本・支店']", "spacy tokens: ['チェーン', '店', '本', '・', '支店']"

## Error Logs/Screenshots
~~~
Document jtest not added to database, because of parse error: 
('Tokens are not aligned!', "hocr tokens: ['チェーン店', '本・支店']", "spacy tokens: ['チェーン', '店本', '・', '支店']")
Traceback (most recent call last):
  File "/home/miyata/work/fonduer/git/fonduer/src/fonduer/parser/parser.py", line 246, in apply
    document.name, document.sentences
  File "/home/miyata/work/fonduer/git/fonduer/src/fonduer/parser/parser.py", line 244, in <listcomp>
    y
  File "/home/miyata/work/fonduer/git/fonduer/src/fonduer/parser/visual_parser/hocr_visual_parser.py", line 135, in parse
    f"spacy tokens: {spacy_tokens}",
RuntimeError: ('Tokens are not aligned!', "hocr tokens: ['チェーン店', '本・支店']", "spacy tokens: ['チェーン', '店本', '・', '支店']")
~~~

## Environment (please complete the following information)
 - OS: Ubuntu 18.04
 - PostgreSQL Version: 10.15
 - Poppler Utils Version: 0.62.0
 - Fonduer Version: 0.8.4+dev
 - Spacy Version: 2.3.1 

## Additional context
I have tried some English hocr examples, but I could not find same problems.

**Comment by HiromuHota** [comment]
@YasushiMiyata The said case is not covered now. I'd appreciate it if you could change the following part of the code to cover this case.
https://github.com/HazyResearch/fonduer/blob/master/src/fonduer/parser/visual_parser/hocr_visual_parser.py#L116-L134

**Comment by YasushiMiyata** [comment]
@HiromuHota Thank you for your advice! I check the code and try to fix it.
